language: go
go:
  - 1.15
env:
  global:
  - CGO_ENABLED=0
go_import_path: github.com/adevinta/vulcan-results
install: _script/bootstrap
script: _script/cibuild
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
